# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'HMIV1.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1111, 867)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.toolBox = QtWidgets.QToolBox(self.centralwidget)
        self.toolBox.setMaximumSize(QtCore.QSize(275, 16777215))
        self.toolBox.setObjectName("toolBox")
        self.PGCamera = QtWidgets.QWidget()
        self.PGCamera.setGeometry(QtCore.QRect(0, 0, 275, 727))
        self.PGCamera.setObjectName("PGCamera")
        self.TABCamera = QtWidgets.QTabWidget(self.PGCamera)
        self.TABCamera.setGeometry(QtCore.QRect(0, 0, 275, 731))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.TABCamera.sizePolicy().hasHeightForWidth())
        self.TABCamera.setSizePolicy(sizePolicy)
        self.TABCamera.setMaximumSize(QtCore.QSize(275, 16777215))
        self.TABCamera.setTabBarAutoHide(False)
        self.TABCamera.setObjectName("TABCamera")
        self.TABDevice = QtWidgets.QWidget()
        self.TABDevice.setObjectName("TABDevice")
        self.groupBox_5 = QtWidgets.QGroupBox(self.TABDevice)
        self.groupBox_5.setGeometry(QtCore.QRect(10, 10, 251, 91))
        self.groupBox_5.setObjectName("groupBox_5")
        self.PBCheckCam = QtWidgets.QPushButton(self.groupBox_5)
        self.PBCheckCam.setGeometry(QtCore.QRect(10, 20, 80, 25))
        self.PBCheckCam.setObjectName("PBCheckCam")
        self.LVCamera = QtWidgets.QListView(self.groupBox_5)
        self.LVCamera.setGeometry(QtCore.QRect(90, 20, 151, 61))
        self.LVCamera.setObjectName("LVCamera")
        self.groupBox_2 = QtWidgets.QGroupBox(self.TABDevice)
        self.groupBox_2.setGeometry(QtCore.QRect(10, 110, 221, 180))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_2.sizePolicy().hasHeightForWidth())
        self.groupBox_2.setSizePolicy(sizePolicy)
        self.groupBox_2.setObjectName("groupBox_2")
        self.CBCamera = QtWidgets.QComboBox(self.groupBox_2)
        self.CBCamera.setGeometry(QtCore.QRect(90, 20, 100, 25))
        self.CBCamera.setObjectName("CBCamera")
        self.PBLive = QtWidgets.QPushButton(self.groupBox_2)
        self.PBLive.setGeometry(QtCore.QRect(10, 20, 75, 25))
        self.PBLive.setObjectName("PBLive")
        self.label = QtWidgets.QLabel(self.groupBox_2)
        self.label.setGeometry(QtCore.QRect(30, 60, 50, 25))
        self.label.setObjectName("label")
        self.DSBExposure = QtWidgets.QDoubleSpinBox(self.groupBox_2)
        self.DSBExposure.setGeometry(QtCore.QRect(110, 60, 81, 25))
        self.DSBExposure.setDecimals(3)
        self.DSBExposure.setMaximum(1000.99)
        self.DSBExposure.setObjectName("DSBExposure")
        self.label_2 = QtWidgets.QLabel(self.groupBox_2)
        self.label_2.setGeometry(QtCore.QRect(200, 60, 20, 25))
        self.label_2.setObjectName("label_2")
        self.label_4 = QtWidgets.QLabel(self.groupBox_2)
        self.label_4.setGeometry(QtCore.QRect(60, 140, 21, 25))
        self.label_4.setObjectName("label_4")
        self.CBBits_2 = QtWidgets.QComboBox(self.groupBox_2)
        self.CBBits_2.setGeometry(QtCore.QRect(110, 140, 60, 25))
        self.CBBits_2.setObjectName("CBBits_2")
        self.CBBits_2.addItem("")
        self.CBBits_2.addItem("")
        self.CBBits_2.addItem("")
        self.CBBits_2.addItem("")
        self.CBBits_2.addItem("")
        self.label_6 = QtWidgets.QLabel(self.groupBox_2)
        self.label_6.setGeometry(QtCore.QRect(9, 100, 71, 25))
        self.label_6.setObjectName("label_6")
        self.SBCGain = QtWidgets.QSpinBox(self.groupBox_2)
        self.SBCGain.setGeometry(QtCore.QRect(110, 100, 75, 25))
        self.SBCGain.setMaximum(240)
        self.SBCGain.setObjectName("SBCGain")
        self.CBBits = QtWidgets.QComboBox(self.groupBox_2)
        self.CBBits.setGeometry(QtCore.QRect(110, 140, 60, 25))
        self.CBBits.setObjectName("CBBits")
        self.CBBits.addItem("")
        self.CBBits.addItem("")
        self.CBBits.addItem("")
        self.groupBox_3 = QtWidgets.QGroupBox(self.TABDevice)
        self.groupBox_3.setGeometry(QtCore.QRect(10, 300, 200, 220))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_3.sizePolicy().hasHeightForWidth())
        self.groupBox_3.setSizePolicy(sizePolicy)
        self.groupBox_3.setObjectName("groupBox_3")
        self.CBBinning = QtWidgets.QComboBox(self.groupBox_3)
        self.CBBinning.setGeometry(QtCore.QRect(90, 20, 60, 25))
        self.CBBinning.setObjectName("CBBinning")
        self.CBBinning.addItem("")
        self.CBBinning.addItem("")
        self.CBBinning.addItem("")
        self.CBBinning.addItem("")
        self.SBXP = QtWidgets.QSpinBox(self.groupBox_3)
        self.SBXP.setEnabled(True)
        self.SBXP.setGeometry(QtCore.QRect(90, 60, 75, 25))
        self.SBXP.setFrame(True)
        self.SBXP.setKeyboardTracking(True)
        self.SBXP.setMaximum(10000)
        self.SBXP.setObjectName("SBXP")
        self.label_5 = QtWidgets.QLabel(self.groupBox_3)
        self.label_5.setGeometry(QtCore.QRect(20, 60, 61, 25))
        self.label_5.setObjectName("label_5")
        self.PBApply = QtWidgets.QPushButton(self.groupBox_3)
        self.PBApply.setGeometry(QtCore.QRect(110, 180, 75, 25))
        self.PBApply.setObjectName("PBApply")
        self.label_3 = QtWidgets.QLabel(self.groupBox_3)
        self.label_3.setGeometry(QtCore.QRect(40, 20, 41, 25))
        self.label_3.setObjectName("label_3")
        self.label_7 = QtWidgets.QLabel(self.groupBox_3)
        self.label_7.setGeometry(QtCore.QRect(20, 90, 61, 25))
        self.label_7.setObjectName("label_7")
        self.SBYP = QtWidgets.QSpinBox(self.groupBox_3)
        self.SBYP.setEnabled(True)
        self.SBYP.setGeometry(QtCore.QRect(90, 90, 75, 25))
        self.SBYP.setFrame(True)
        self.SBYP.setKeyboardTracking(True)
        self.SBYP.setMaximum(10000)
        self.SBYP.setObjectName("SBYP")
        self.CBBinning_2 = QtWidgets.QComboBox(self.groupBox_3)
        self.CBBinning_2.setGeometry(QtCore.QRect(90, 20, 60, 25))
        self.CBBinning_2.setObjectName("CBBinning_2")
        self.CBBinning_2.addItem("")
        self.CBBinning_2.addItem("")
        self.CBBinning_2.addItem("")
        self.SBWidth = QtWidgets.QSpinBox(self.groupBox_3)
        self.SBWidth.setEnabled(True)
        self.SBWidth.setGeometry(QtCore.QRect(90, 120, 75, 25))
        self.SBWidth.setFrame(True)
        self.SBWidth.setKeyboardTracking(True)
        self.SBWidth.setMaximum(10000)
        self.SBWidth.setObjectName("SBWidth")
        self.PBReset = QtWidgets.QPushButton(self.groupBox_3)
        self.PBReset.setGeometry(QtCore.QRect(20, 180, 75, 25))
        self.PBReset.setObjectName("PBReset")
        self.label_9 = QtWidgets.QLabel(self.groupBox_3)
        self.label_9.setGeometry(QtCore.QRect(20, 150, 61, 25))
        self.label_9.setObjectName("label_9")
        self.SBHeight = QtWidgets.QSpinBox(self.groupBox_3)
        self.SBHeight.setEnabled(True)
        self.SBHeight.setGeometry(QtCore.QRect(90, 150, 75, 25))
        self.SBHeight.setFrame(True)
        self.SBHeight.setKeyboardTracking(True)
        self.SBHeight.setMaximum(10000)
        self.SBHeight.setObjectName("SBHeight")
        self.label_8 = QtWidgets.QLabel(self.groupBox_3)
        self.label_8.setGeometry(QtCore.QRect(20, 120, 61, 25))
        self.label_8.setObjectName("label_8")
        self.TABCamera.addTab(self.TABDevice, "")
        self.TABBackground = QtWidgets.QWidget()
        self.TABBackground.setObjectName("TABBackground")
        self.groupBox_4 = QtWidgets.QGroupBox(self.TABBackground)
        self.groupBox_4.setGeometry(QtCore.QRect(10, 0, 251, 541))
        self.groupBox_4.setObjectName("groupBox_4")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.groupBox_4)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(0, 20, 251, 521))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.TBBGK = QtWidgets.QToolBox(self.verticalLayoutWidget)
        self.TBBGK.setEnabled(True)
        self.TBBGK.setObjectName("TBBGK")
        self.POriginal = QtWidgets.QWidget()
        self.POriginal.setGeometry(QtCore.QRect(0, 0, 249, 222))
        self.POriginal.setObjectName("POriginal")
        self.RBImage = QtWidgets.QRadioButton(self.POriginal)
        self.RBImage.setGeometry(QtCore.QRect(20, 10, 171, 17))
        self.RBImage.setChecked(True)
        self.RBImage.setObjectName("RBImage")
        self.TBBGK.addItem(self.POriginal, "")
        self.PBKGCNT = QtWidgets.QWidget()
        self.PBKGCNT.setGeometry(QtCore.QRect(0, 0, 249, 222))
        self.PBKGCNT.setObjectName("PBKGCNT")
        self.SBMaxPS = QtWidgets.QSpinBox(self.PBKGCNT)
        self.SBMaxPS.setGeometry(QtCore.QRect(150, 70, 75, 25))
        self.SBMaxPS.setMaximum(1000)
        self.SBMaxPS.setProperty("value", 900)
        self.SBMaxPS.setObjectName("SBMaxPS")
        self.label_16 = QtWidgets.QLabel(self.PBKGCNT)
        self.label_16.setGeometry(QtCore.QRect(50, 70, 91, 16))
        self.label_16.setObjectName("label_16")
        self.RBTCNT = QtWidgets.QRadioButton(self.PBKGCNT)
        self.RBTCNT.setGeometry(QtCore.QRect(20, 10, 171, 17))
        self.RBTCNT.setObjectName("RBTCNT")
        self.SBMinPS = QtWidgets.QSpinBox(self.PBKGCNT)
        self.SBMinPS.setGeometry(QtCore.QRect(150, 40, 75, 25))
        self.SBMinPS.setProperty("value", 15)
        self.SBMinPS.setObjectName("SBMinPS")
        self.label_15 = QtWidgets.QLabel(self.PBKGCNT)
        self.label_15.setGeometry(QtCore.QRect(50, 40, 91, 21))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.label_15.setFont(font)
        self.label_15.setIndent(-1)
        self.label_15.setObjectName("label_15")
        self.CBHistory = QtWidgets.QCheckBox(self.PBKGCNT)
        self.CBHistory.setGeometry(QtCore.QRect(50, 100, 91, 17))
        self.CBHistory.setChecked(True)
        self.CBHistory.setTristate(False)
        self.CBHistory.setObjectName("CBHistory")
        self.CBIsParallel = QtWidgets.QCheckBox(self.PBKGCNT)
        self.CBIsParallel.setGeometry(QtCore.QRect(50, 130, 70, 17))
        self.CBIsParallel.setChecked(True)
        self.CBIsParallel.setObjectName("CBIsParallel")
        self.TBBGK.addItem(self.PBKGCNT, "")
        self.PBKGGMG = QtWidgets.QWidget()
        self.PBKGGMG.setObjectName("PBKGGMG")
        self.DSBThreshold = QtWidgets.QDoubleSpinBox(self.PBKGGMG)
        self.DSBThreshold.setGeometry(QtCore.QRect(150, 70, 75, 25))
        self.DSBThreshold.setProperty("value", 0.8)
        self.DSBThreshold.setObjectName("DSBThreshold")
        self.SBInitialF = QtWidgets.QSpinBox(self.PBKGGMG)
        self.SBInitialF.setGeometry(QtCore.QRect(150, 40, 75, 25))
        self.SBInitialF.setProperty("value", 1)
        self.SBInitialF.setObjectName("SBInitialF")
        self.label_17 = QtWidgets.QLabel(self.PBKGGMG)
        self.label_17.setGeometry(QtCore.QRect(50, 40, 91, 16))
        self.label_17.setObjectName("label_17")
        self.label_18 = QtWidgets.QLabel(self.PBKGGMG)
        self.label_18.setGeometry(QtCore.QRect(50, 70, 91, 16))
        self.label_18.setObjectName("label_18")
        self.RBTGMG = QtWidgets.QRadioButton(self.PBKGGMG)
        self.RBTGMG.setGeometry(QtCore.QRect(20, 10, 171, 17))
        self.RBTGMG.setObjectName("RBTGMG")
        self.TBBGK.addItem(self.PBKGGMG, "")
        self.PBKGGSOC = QtWidgets.QWidget()
        self.PBKGGSOC.setObjectName("PBKGGSOC")
        self.RBTGSOC = QtWidgets.QRadioButton(self.PBKGGSOC)
        self.RBTGSOC.setGeometry(QtCore.QRect(20, 10, 171, 17))
        self.RBTGSOC.setObjectName("RBTGSOC")
        self.label_19 = QtWidgets.QLabel(self.PBKGGSOC)
        self.label_19.setGeometry(QtCore.QRect(46, 30, 61, 21))
        self.label_19.setObjectName("label_19")
        self.SBNSamples = QtWidgets.QSpinBox(self.PBKGGSOC)
        self.SBNSamples.setGeometry(QtCore.QRect(120, 30, 75, 25))
        self.SBNSamples.setProperty("value", 20)
        self.SBNSamples.setObjectName("SBNSamples")
        self.label_20 = QtWidgets.QLabel(self.PBKGGSOC)
        self.label_20.setGeometry(QtCore.QRect(50, 60, 51, 21))
        self.label_20.setObjectName("label_20")
        self.SBNThreshold = QtWidgets.QSpinBox(self.PBKGGSOC)
        self.SBNThreshold.setGeometry(QtCore.QRect(120, 60, 75, 25))
        self.SBNThreshold.setProperty("value", 32)
        self.SBNThreshold.setObjectName("SBNThreshold")
        self.label_21 = QtWidgets.QLabel(self.PBKGGSOC)
        self.label_21.setGeometry(QtCore.QRect(36, 90, 71, 21))
        self.label_21.setObjectName("label_21")
        self.DSBReplace = QtWidgets.QDoubleSpinBox(self.PBKGGSOC)
        self.DSBReplace.setGeometry(QtCore.QRect(120, 90, 75, 25))
        self.DSBReplace.setDecimals(3)
        self.DSBReplace.setProperty("value", 0.003)
        self.DSBReplace.setObjectName("DSBReplace")
        self.DSBalpha = QtWidgets.QDoubleSpinBox(self.PBKGGSOC)
        self.DSBalpha.setGeometry(QtCore.QRect(120, 120, 75, 25))
        self.DSBalpha.setDecimals(3)
        self.DSBalpha.setProperty("value", 0.01)
        self.DSBalpha.setObjectName("DSBalpha")
        self.label_22 = QtWidgets.QLabel(self.PBKGGSOC)
        self.label_22.setGeometry(QtCore.QRect(50, 120, 61, 21))
        self.label_22.setObjectName("label_22")
        self.label_23 = QtWidgets.QLabel(self.PBKGGSOC)
        self.label_23.setGeometry(QtCore.QRect(50, 150, 61, 21))
        self.label_23.setObjectName("label_23")
        self.DSBBeta = QtWidgets.QDoubleSpinBox(self.PBKGGSOC)
        self.DSBBeta.setGeometry(QtCore.QRect(120, 150, 75, 25))
        self.DSBBeta.setDecimals(3)
        self.DSBBeta.setProperty("value", 0.002)
        self.DSBBeta.setObjectName("DSBBeta")
        self.label_24 = QtWidgets.QLabel(self.PBKGGSOC)
        self.label_24.setGeometry(QtCore.QRect(20, 180, 91, 21))
        self.label_24.setObjectName("label_24")
        self.DSBPropagation = QtWidgets.QDoubleSpinBox(self.PBKGGSOC)
        self.DSBPropagation.setGeometry(QtCore.QRect(120, 180, 75, 25))
        self.DSBPropagation.setProperty("value", 0.01)
        self.DSBPropagation.setObjectName("DSBPropagation")
        self.TBBGK.addItem(self.PBKGGSOC, "")
        self.PBKGKNN = QtWidgets.QWidget()
        self.PBKGKNN.setObjectName("PBKGKNN")
        self.RBTKNN = QtWidgets.QRadioButton(self.PBKGKNN)
        self.RBTKNN.setGeometry(QtCore.QRect(20, 10, 171, 17))
        self.RBTKNN.setObjectName("RBTKNN")
        self.label_25 = QtWidgets.QLabel(self.PBKGKNN)
        self.label_25.setGeometry(QtCore.QRect(60, 40, 47, 13))
        self.label_25.setObjectName("label_25")
        self.label_26 = QtWidgets.QLabel(self.PBKGKNN)
        self.label_26.setGeometry(QtCore.QRect(16, 80, 91, 20))
        self.label_26.setObjectName("label_26")
        self.checkBox = QtWidgets.QCheckBox(self.PBKGKNN)
        self.checkBox.setGeometry(QtCore.QRect(60, 120, 111, 17))
        self.checkBox.setChecked(True)
        self.checkBox.setObjectName("checkBox")
        self.SBHistory = QtWidgets.QSpinBox(self.PBKGKNN)
        self.SBHistory.setGeometry(QtCore.QRect(120, 40, 75, 25))
        self.SBHistory.setMaximum(1000)
        self.SBHistory.setProperty("value", 500)
        self.SBHistory.setObjectName("SBHistory")
        self.DSBThreshold_2 = QtWidgets.QDoubleSpinBox(self.PBKGKNN)
        self.DSBThreshold_2.setGeometry(QtCore.QRect(120, 80, 75, 25))
        self.DSBThreshold_2.setMaximum(1000.0)
        self.DSBThreshold_2.setProperty("value", 400.0)
        self.DSBThreshold_2.setObjectName("DSBThreshold_2")
        self.TBBGK.addItem(self.PBKGKNN, "")
        self.PBKGLSBP = QtWidgets.QWidget()
        self.PBKGLSBP.setObjectName("PBKGLSBP")
        self.RBTLSBP = QtWidgets.QRadioButton(self.PBKGLSBP)
        self.RBTLSBP.setGeometry(QtCore.QRect(20, 0, 171, 17))
        self.RBTLSBP.setObjectName("RBTLSBP")
        self.label_27 = QtWidgets.QLabel(self.PBKGLSBP)
        self.label_27.setGeometry(QtCore.QRect(50, 30, 61, 16))
        self.label_27.setObjectName("label_27")
        self.SBNSamplesLSBP = QtWidgets.QSpinBox(self.PBKGLSBP)
        self.SBNSamplesLSBP.setGeometry(QtCore.QRect(120, 20, 75, 25))
        self.SBNSamplesLSBP.setProperty("value", 20)
        self.SBNSamplesLSBP.setObjectName("SBNSamplesLSBP")
        self.label_28 = QtWidgets.QLabel(self.PBKGLSBP)
        self.label_28.setGeometry(QtCore.QRect(40, 60, 71, 16))
        self.label_28.setObjectName("label_28")
        self.SBLRadius = QtWidgets.QSpinBox(self.PBKGLSBP)
        self.SBLRadius.setGeometry(QtCore.QRect(120, 60, 75, 25))
        self.SBLRadius.setProperty("value", 16)
        self.SBLRadius.setObjectName("SBLRadius")
        self.label_29 = QtWidgets.QLabel(self.PBKGLSBP)
        self.label_29.setGeometry(QtCore.QRect(54, 120, 61, 21))
        self.label_29.setObjectName("label_29")
        self.DSRScale = QtWidgets.QDoubleSpinBox(self.PBKGLSBP)
        self.DSRScale.setGeometry(QtCore.QRect(120, 120, 75, 25))
        self.DSRScale.setProperty("value", 10.0)
        self.DSRScale.setObjectName("DSRScale")
        self.label_30 = QtWidgets.QLabel(self.PBKGLSBP)
        self.label_30.setGeometry(QtCore.QRect(24, 150, 91, 21))
        self.label_30.setObjectName("label_30")
        self.DSBLThreshold = QtWidgets.QDoubleSpinBox(self.PBKGLSBP)
        self.DSBLThreshold.setGeometry(QtCore.QRect(120, 150, 75, 25))
        self.DSBLThreshold.setMaximum(1000.0)
        self.DSBLThreshold.setProperty("value", 8.0)
        self.DSBLThreshold.setObjectName("DSBLThreshold")
        self.DSBPmCount = QtWidgets.QDoubleSpinBox(self.PBKGLSBP)
        self.DSBPmCount.setGeometry(QtCore.QRect(120, 190, 75, 25))
        self.DSBPmCount.setProperty("value", 2.0)
        self.DSBPmCount.setObjectName("DSBPmCount")
        self.label_32 = QtWidgets.QLabel(self.PBKGLSBP)
        self.label_32.setGeometry(QtCore.QRect(24, 180, 91, 21))
        self.label_32.setObjectName("label_32")
        self.DSBTupper = QtWidgets.QDoubleSpinBox(self.PBKGLSBP)
        self.DSBTupper.setGeometry(QtCore.QRect(120, 90, 75, 25))
        self.DSBTupper.setProperty("value", 32.0)
        self.DSBTupper.setObjectName("DSBTupper")
        self.label_33 = QtWidgets.QLabel(self.PBKGLSBP)
        self.label_33.setGeometry(QtCore.QRect(40, 90, 71, 21))
        self.label_33.setObjectName("label_33")
        self.TBBGK.addItem(self.PBKGLSBP, "")
        self.PBKGMOG = QtWidgets.QWidget()
        self.PBKGMOG.setObjectName("PBKGMOG")
        self.RBTMOG = QtWidgets.QRadioButton(self.PBKGMOG)
        self.RBTMOG.setGeometry(QtCore.QRect(20, 0, 171, 17))
        self.RBTMOG.setObjectName("RBTMOG")
        self.label_31 = QtWidgets.QLabel(self.PBKGMOG)
        self.label_31.setGeometry(QtCore.QRect(50, 30, 47, 13))
        self.label_31.setObjectName("label_31")
        self.SBHistoryMOG = QtWidgets.QSpinBox(self.PBKGMOG)
        self.SBHistoryMOG.setGeometry(QtCore.QRect(110, 20, 75, 25))
        self.SBHistoryMOG.setMaximum(10000)
        self.SBHistoryMOG.setProperty("value", 200)
        self.SBHistoryMOG.setObjectName("SBHistoryMOG")
        self.SBMixtures = QtWidgets.QSpinBox(self.PBKGMOG)
        self.SBMixtures.setGeometry(QtCore.QRect(110, 50, 75, 25))
        self.SBMixtures.setMaximum(200)
        self.SBMixtures.setProperty("value", 5)
        self.SBMixtures.setObjectName("SBMixtures")
        self.label_34 = QtWidgets.QLabel(self.PBKGMOG)
        self.label_34.setGeometry(QtCore.QRect(40, 50, 71, 20))
        self.label_34.setObjectName("label_34")
        self.DSBRatio = QtWidgets.QDoubleSpinBox(self.PBKGMOG)
        self.DSBRatio.setGeometry(QtCore.QRect(110, 80, 75, 25))
        self.DSBRatio.setMaximum(1000.0)
        self.DSBRatio.setProperty("value", 0.7)
        self.DSBRatio.setObjectName("DSBRatio")
        self.label_35 = QtWidgets.QLabel(self.PBKGMOG)
        self.label_35.setGeometry(QtCore.QRect(10, 80, 101, 20))
        self.label_35.setObjectName("label_35")
        self.SBNoise = QtWidgets.QSpinBox(self.PBKGMOG)
        self.SBNoise.setGeometry(QtCore.QRect(110, 110, 75, 25))
        self.SBNoise.setMaximum(100)
        self.SBNoise.setObjectName("SBNoise")
        self.label_36 = QtWidgets.QLabel(self.PBKGMOG)
        self.label_36.setGeometry(QtCore.QRect(30, 110, 71, 20))
        self.label_36.setObjectName("label_36")
        self.TBBGK.addItem(self.PBKGMOG, "")
        self.PBKGMOG2 = QtWidgets.QWidget()
        self.PBKGMOG2.setObjectName("PBKGMOG2")
        self.RBTMOG2 = QtWidgets.QRadioButton(self.PBKGMOG2)
        self.RBTMOG2.setGeometry(QtCore.QRect(20, 0, 171, 17))
        self.RBTMOG2.setObjectName("RBTMOG2")
        self.label_37 = QtWidgets.QLabel(self.PBKGMOG2)
        self.label_37.setGeometry(QtCore.QRect(50, 30, 47, 13))
        self.label_37.setObjectName("label_37")
        self.SBHistoryMOG2 = QtWidgets.QSpinBox(self.PBKGMOG2)
        self.SBHistoryMOG2.setGeometry(QtCore.QRect(110, 20, 75, 25))
        self.SBHistoryMOG2.setMaximum(1000)
        self.SBHistoryMOG2.setProperty("value", 500)
        self.SBHistoryMOG2.setObjectName("SBHistoryMOG2")
        self.SBThresholdMOG2 = QtWidgets.QSpinBox(self.PBKGMOG2)
        self.SBThresholdMOG2.setGeometry(QtCore.QRect(110, 50, 75, 25))
        self.SBThresholdMOG2.setMaximum(1000)
        self.SBThresholdMOG2.setProperty("value", 16)
        self.SBThresholdMOG2.setObjectName("SBThresholdMOG2")
        self.label_38 = QtWidgets.QLabel(self.PBKGMOG2)
        self.label_38.setGeometry(QtCore.QRect(50, 60, 47, 13))
        self.label_38.setObjectName("label_38")
        self.CBDshadowsMOG2 = QtWidgets.QCheckBox(self.PBKGMOG2)
        self.CBDshadowsMOG2.setGeometry(QtCore.QRect(90, 90, 70, 17))
        self.CBDshadowsMOG2.setChecked(True)
        self.CBDshadowsMOG2.setObjectName("CBDshadowsMOG2")
        self.TBBGK.addItem(self.PBKGMOG2, "")
        self.PBKGRNB = QtWidgets.QWidget()
        self.PBKGRNB.setObjectName("PBKGRNB")
        self.RBTRNB = QtWidgets.QRadioButton(self.PBKGRNB)
        self.RBTRNB.setGeometry(QtCore.QRect(20, 0, 171, 17))
        self.RBTRNB.setObjectName("RBTRNB")
        self.label_39 = QtWidgets.QLabel(self.PBKGRNB)
        self.label_39.setGeometry(QtCore.QRect(50, 30, 47, 13))
        self.label_39.setObjectName("label_39")
        self.DSBAlpha = QtWidgets.QDoubleSpinBox(self.PBKGRNB)
        self.DSBAlpha.setGeometry(QtCore.QRect(100, 20, 75, 25))
        self.DSBAlpha.setMaximum(1000.0)
        self.DSBAlpha.setProperty("value", 0.9)
        self.DSBAlpha.setObjectName("DSBAlpha")
        self.label_40 = QtWidgets.QLabel(self.PBKGRNB)
        self.label_40.setGeometry(QtCore.QRect(16, 60, 71, 20))
        self.label_40.setObjectName("label_40")
        self.SBThu = QtWidgets.QSpinBox(self.PBKGRNB)
        self.SBThu.setGeometry(QtCore.QRect(100, 60, 75, 25))
        self.SBThu.setMaximum(300)
        self.SBThu.setProperty("value", 30)
        self.SBThu.setObjectName("SBThu")
        self.SBThs = QtWidgets.QSpinBox(self.PBKGRNB)
        self.SBThs.setGeometry(QtCore.QRect(100, 100, 75, 25))
        self.SBThs.setMaximum(1000)
        self.SBThs.setProperty("value", 30)
        self.SBThs.setObjectName("SBThs")
        self.label_41 = QtWidgets.QLabel(self.PBKGRNB)
        self.label_41.setGeometry(QtCore.QRect(20, 100, 71, 20))
        self.label_41.setObjectName("label_41")
        self.TBBGK.addItem(self.PBKGRNB, "")
        self.PBKGFZBL = QtWidgets.QWidget()
        self.PBKGFZBL.setObjectName("PBKGFZBL")
        self.RBTFZBL = QtWidgets.QRadioButton(self.PBKGFZBL)
        self.RBTFZBL.setGeometry(QtCore.QRect(20, 10, 171, 17))
        self.RBTFZBL.setObjectName("RBTFZBL")
        self.label_42 = QtWidgets.QLabel(self.PBKGFZBL)
        self.label_42.setGeometry(QtCore.QRect(44, 120, 71, 20))
        self.label_42.setObjectName("label_42")
        self.SBThSFL = QtWidgets.QSpinBox(self.PBKGFZBL)
        self.SBThSFL.setGeometry(QtCore.QRect(124, 80, 75, 25))
        self.SBThSFL.setProperty("value", 30)
        self.SBThSFL.setObjectName("SBThSFL")
        self.DSBAlphaFL = QtWidgets.QDoubleSpinBox(self.PBKGFZBL)
        self.DSBAlphaFL.setGeometry(QtCore.QRect(124, 40, 75, 25))
        self.DSBAlphaFL.setProperty("value", 0.9)
        self.DSBAlphaFL.setObjectName("DSBAlphaFL")
        self.label_43 = QtWidgets.QLabel(self.PBKGFZBL)
        self.label_43.setGeometry(QtCore.QRect(74, 50, 47, 13))
        self.label_43.setObjectName("label_43")
        self.label_44 = QtWidgets.QLabel(self.PBKGFZBL)
        self.label_44.setGeometry(QtCore.QRect(40, 80, 71, 20))
        self.label_44.setObjectName("label_44")
        self.DSBThfsFL = QtWidgets.QDoubleSpinBox(self.PBKGFZBL)
        self.DSBThfsFL.setGeometry(QtCore.QRect(120, 120, 75, 25))
        self.DSBThfsFL.setMaximum(1000.0)
        self.DSBThfsFL.setProperty("value", 0.4)
        self.DSBThfsFL.setObjectName("DSBThfsFL")
        self.TBBGK.addItem(self.PBKGFZBL, "")
        self.PBKGFZB = QtWidgets.QWidget()
        self.PBKGFZB.setObjectName("PBKGFZB")
        self.RBTFZB = QtWidgets.QRadioButton(self.PBKGFZB)
        self.RBTFZB.setGeometry(QtCore.QRect(20, 10, 171, 17))
        self.RBTFZB.setObjectName("RBTFZB")
        self.SBThSFZB = QtWidgets.QSpinBox(self.PBKGFZB)
        self.SBThSFZB.setGeometry(QtCore.QRect(130, 120, 75, 25))
        self.SBThSFZB.setProperty("value", 30)
        self.SBThSFZB.setObjectName("SBThSFZB")
        self.label_45 = QtWidgets.QLabel(self.PBKGFZB)
        self.label_45.setGeometry(QtCore.QRect(46, 120, 71, 20))
        self.label_45.setObjectName("label_45")
        self.label_46 = QtWidgets.QLabel(self.PBKGFZB)
        self.label_46.setGeometry(QtCore.QRect(50, 150, 71, 20))
        self.label_46.setObjectName("label_46")
        self.label_47 = QtWidgets.QLabel(self.PBKGFZB)
        self.label_47.setGeometry(QtCore.QRect(80, 50, 47, 13))
        self.label_47.setObjectName("label_47")
        self.DSBAlphaFZB = QtWidgets.QDoubleSpinBox(self.PBKGFZB)
        self.DSBAlphaFZB.setGeometry(QtCore.QRect(130, 40, 75, 25))
        self.DSBAlphaFZB.setProperty("value", 0.4)
        self.DSBAlphaFZB.setObjectName("DSBAlphaFZB")
        self.label_48 = QtWidgets.QLabel(self.PBKGFZB)
        self.label_48.setGeometry(QtCore.QRect(66, 80, 61, 20))
        self.label_48.setObjectName("label_48")
        self.DSBAlphaFZB_2 = QtWidgets.QDoubleSpinBox(self.PBKGFZB)
        self.DSBAlphaFZB_2.setGeometry(QtCore.QRect(130, 80, 75, 25))
        self.DSBAlphaFZB_2.setProperty("value", 0.9)
        self.DSBAlphaFZB_2.setObjectName("DSBAlphaFZB_2")
        self.DSBThfsFZB = QtWidgets.QDoubleSpinBox(self.PBKGFZB)
        self.DSBThfsFZB.setGeometry(QtCore.QRect(130, 150, 75, 25))
        self.DSBThfsFZB.setMaximum(1000.0)
        self.DSBThfsFZB.setProperty("value", 0.4)
        self.DSBThfsFZB.setObjectName("DSBThfsFZB")
        self.TBBGK.addItem(self.PBKGFZB, "")
        self.verticalLayout.addWidget(self.TBBGK)
        self.groupBox_6 = QtWidgets.QGroupBox(self.TABBackground)
        self.groupBox_6.setGeometry(QtCore.QRect(10, 540, 251, 171))
        self.groupBox_6.setObjectName("groupBox_6")
        self.RBOFrame = QtWidgets.QRadioButton(self.groupBox_6)
        self.RBOFrame.setGeometry(QtCore.QRect(10, 15, 101, 17))
        self.RBOFrame.setChecked(True)
        self.RBOFrame.setObjectName("RBOFrame")
        self.RBBFrame = QtWidgets.QRadioButton(self.groupBox_6)
        self.RBBFrame.setGeometry(QtCore.QRect(10, 35, 121, 17))
        self.RBBFrame.setObjectName("RBBFrame")
        self.RBFFrame = QtWidgets.QRadioButton(self.groupBox_6)
        self.RBFFrame.setGeometry(QtCore.QRect(10, 55, 121, 17))
        self.RBFFrame.setObjectName("RBFFrame")
        self.RBImg = QtWidgets.QRadioButton(self.groupBox_6)
        self.RBImg.setGeometry(QtCore.QRect(10, 75, 121, 17))
        self.RBImg.setObjectName("RBImg")
        self.label_49 = QtWidgets.QLabel(self.groupBox_6)
        self.label_49.setGeometry(QtCore.QRect(50, 95, 47, 13))
        self.label_49.setObjectName("label_49")
        self.label_51 = QtWidgets.QLabel(self.groupBox_6)
        self.label_51.setGeometry(QtCore.QRect(150, 95, 47, 13))
        self.label_51.setObjectName("label_51")
        self.DSBBetaI = QtWidgets.QDoubleSpinBox(self.groupBox_6)
        self.DSBBetaI.setGeometry(QtCore.QRect(170, 90, 62, 22))
        self.DSBBetaI.setProperty("value", 0.75)
        self.DSBBetaI.setObjectName("DSBBetaI")
        self.DSBAlphaI = QtWidgets.QDoubleSpinBox(self.groupBox_6)
        self.DSBAlphaI.setGeometry(QtCore.QRect(70, 90, 62, 22))
        self.DSBAlphaI.setProperty("value", 0.25)
        self.DSBAlphaI.setObjectName("DSBAlphaI")
        self.PBApplyBGK = QtWidgets.QPushButton(self.groupBox_6)
        self.PBApplyBGK.setGeometry(QtCore.QRect(160, 20, 45, 45))
        self.PBApplyBGK.setObjectName("PBApplyBGK")
        self.groupBox_13 = QtWidgets.QGroupBox(self.groupBox_6)
        self.groupBox_13.setGeometry(QtCore.QRect(10, 115, 230, 50))
        self.groupBox_13.setTitle("")
        self.groupBox_13.setObjectName("groupBox_13")
        self.DSBBetaL = QtWidgets.QDoubleSpinBox(self.groupBox_13)
        self.DSBBetaL.setGeometry(QtCore.QRect(160, 20, 62, 22))
        self.DSBBetaL.setProperty("value", 0.5)
        self.DSBBetaL.setObjectName("DSBBetaL")
        self.RBLImg = QtWidgets.QRadioButton(self.groupBox_13)
        self.RBLImg.setGeometry(QtCore.QRect(0, 4, 121, 17))
        self.RBLImg.setObjectName("RBLImg")
        self.DSBAlphaL = QtWidgets.QDoubleSpinBox(self.groupBox_13)
        self.DSBAlphaL.setGeometry(QtCore.QRect(60, 20, 62, 22))
        self.DSBAlphaL.setProperty("value", 0.95)
        self.DSBAlphaL.setObjectName("DSBAlphaL")
        self.label_50 = QtWidgets.QLabel(self.groupBox_13)
        self.label_50.setGeometry(QtCore.QRect(40, 30, 47, 13))
        self.label_50.setObjectName("label_50")
        self.label_52 = QtWidgets.QLabel(self.groupBox_13)
        self.label_52.setGeometry(QtCore.QRect(140, 30, 47, 13))
        self.label_52.setObjectName("label_52")
        self.TABCamera.addTab(self.TABBackground, "")
        self.TABFilters = QtWidgets.QWidget()
        self.TABFilters.setObjectName("TABFilters")
        self.TABCamera.addTab(self.TABFilters, "")
        self.TABGet = QtWidgets.QWidget()
        self.TABGet.setObjectName("TABGet")
        self.groupBox_9 = QtWidgets.QGroupBox(self.TABGet)
        self.groupBox_9.setGeometry(QtCore.QRect(0, 10, 261, 251))
        self.groupBox_9.setObjectName("groupBox_9")
        self.PBRecording = QtWidgets.QProgressBar(self.groupBox_9)
        self.PBRecording.setGeometry(QtCore.QRect(10, 200, 161, 23))
        self.PBRecording.setProperty("value", 0)
        self.PBRecording.setObjectName("PBRecording")
        self.PBSetF = QtWidgets.QPushButton(self.groupBox_9)
        self.PBSetF.setGeometry(QtCore.QRect(10, 20, 75, 25))
        self.PBSetF.setObjectName("PBSetF")
        self.groupBox = QtWidgets.QGroupBox(self.groupBox_9)
        self.groupBox.setGeometry(QtCore.QRect(10, 50, 201, 101))
        self.groupBox.setObjectName("groupBox")
        self.RBFrames = QtWidgets.QRadioButton(self.groupBox)
        self.RBFrames.setGeometry(QtCore.QRect(10, 30, 82, 17))
        self.RBFrames.setObjectName("RBFrames")
        self.RBtime = QtWidgets.QRadioButton(self.groupBox)
        self.RBtime.setGeometry(QtCore.QRect(10, 60, 82, 17))
        self.RBtime.setChecked(True)
        self.RBtime.setObjectName("RBtime")
        self.SBFrames = QtWidgets.QSpinBox(self.groupBox)
        self.SBFrames.setGeometry(QtCore.QRect(90, 20, 75, 25))
        self.SBFrames.setMaximum(10000)
        self.SBFrames.setProperty("value", 30)
        self.SBFrames.setObjectName("SBFrames")
        self.DSBTime = QtWidgets.QDoubleSpinBox(self.groupBox)
        self.DSBTime.setGeometry(QtCore.QRect(90, 50, 75, 25))
        self.DSBTime.setMaximum(10000.99)
        self.DSBTime.setProperty("value", 1.0)
        self.DSBTime.setObjectName("DSBTime")
        self.label_10 = QtWidgets.QLabel(self.groupBox)
        self.label_10.setGeometry(QtCore.QRect(170, 60, 21, 16))
        self.label_10.setObjectName("label_10")
        self.PBAcquire = QtWidgets.QPushButton(self.groupBox_9)
        self.PBAcquire.setEnabled(True)
        self.PBAcquire.setGeometry(QtCore.QRect(100, 160, 75, 25))
        self.PBAcquire.setObjectName("PBAcquire")
        self.LEFileP = QtWidgets.QLineEdit(self.groupBox_9)
        self.LEFileP.setGeometry(QtCore.QRect(90, 20, 131, 25))
        self.LEFileP.setObjectName("LEFileP")
        self.PBLive_2 = QtWidgets.QPushButton(self.groupBox_9)
        self.PBLive_2.setGeometry(QtCore.QRect(10, 160, 75, 25))
        self.PBLive_2.setObjectName("PBLive_2")
        self.groupBox_10 = QtWidgets.QGroupBox(self.TABGet)
        self.groupBox_10.setGeometry(QtCore.QRect(0, 270, 261, 221))
        self.groupBox_10.setObjectName("groupBox_10")
        self.label_53 = QtWidgets.QLabel(self.groupBox_10)
        self.label_53.setGeometry(QtCore.QRect(50, 30, 71, 21))
        self.label_53.setObjectName("label_53")
        self.label_54 = QtWidgets.QLabel(self.groupBox_10)
        self.label_54.setGeometry(QtCore.QRect(80, 60, 51, 16))
        self.label_54.setObjectName("label_54")
        self.label_55 = QtWidgets.QLabel(self.groupBox_10)
        self.label_55.setGeometry(QtCore.QRect(80, 90, 51, 16))
        self.label_55.setObjectName("label_55")
        self.label_56 = QtWidgets.QLabel(self.groupBox_10)
        self.label_56.setGeometry(QtCore.QRect(20, 120, 101, 21))
        self.label_56.setObjectName("label_56")
        self.label_57 = QtWidgets.QLabel(self.groupBox_10)
        self.label_57.setGeometry(QtCore.QRect(50, 150, 61, 21))
        self.label_57.setObjectName("label_57")
        self.LEFrameRate = QtWidgets.QLineEdit(self.groupBox_10)
        self.LEFrameRate.setGeometry(QtCore.QRect(120, 30, 75, 25))
        self.LEFrameRate.setObjectName("LEFrameRate")
        self.LEDate = QtWidgets.QLineEdit(self.groupBox_10)
        self.LEDate.setGeometry(QtCore.QRect(120, 60, 75, 25))
        self.LEDate.setObjectName("LEDate")
        self.LEHour = QtWidgets.QLineEdit(self.groupBox_10)
        self.LEHour.setGeometry(QtCore.QRect(120, 90, 75, 25))
        self.LEHour.setObjectName("LEHour")
        self.LENFrames = QtWidgets.QLineEdit(self.groupBox_10)
        self.LENFrames.setGeometry(QtCore.QRect(120, 120, 75, 25))
        self.LENFrames.setObjectName("LENFrames")
        self.LETime = QtWidgets.QLineEdit(self.groupBox_10)
        self.LETime.setGeometry(QtCore.QRect(120, 150, 75, 25))
        self.LETime.setObjectName("LETime")
        self.TABCamera.addTab(self.TABGet, "")
        self.toolBox.addItem(self.PGCamera, "")
        self.PGFEditor = QtWidgets.QWidget()
        self.PGFEditor.setGeometry(QtCore.QRect(0, 0, 275, 727))
        self.PGFEditor.setObjectName("PGFEditor")
        self.groupBox_7 = QtWidgets.QGroupBox(self.PGFEditor)
        self.groupBox_7.setGeometry(QtCore.QRect(0, 0, 271, 701))
        self.groupBox_7.setObjectName("groupBox_7")
        self.PBFolderFrame = QtWidgets.QPushButton(self.groupBox_7)
        self.PBFolderFrame.setGeometry(QtCore.QRect(10, 20, 75, 25))
        self.PBFolderFrame.setObjectName("PBFolderFrame")
        self.LEPATH = QtWidgets.QLineEdit(self.groupBox_7)
        self.LEPATH.setGeometry(QtCore.QRect(100, 20, 151, 25))
        self.LEPATH.setObjectName("LEPATH")
        self.PBOutputF = QtWidgets.QPushButton(self.groupBox_7)
        self.PBOutputF.setGeometry(QtCore.QRect(10, 290, 75, 25))
        self.PBOutputF.setObjectName("PBOutputF")
        self.LEOutPath = QtWidgets.QLineEdit(self.groupBox_7)
        self.LEOutPath.setGeometry(QtCore.QRect(100, 290, 151, 25))
        self.LEOutPath.setObjectName("LEOutPath")
        self.label_13 = QtWidgets.QLabel(self.groupBox_7)
        self.label_13.setGeometry(QtCore.QRect(20, 330, 71, 20))
        self.label_13.setObjectName("label_13")
        self.SBFrameRate = QtWidgets.QSpinBox(self.groupBox_7)
        self.SBFrameRate.setGeometry(QtCore.QRect(100, 330, 75, 25))
        self.SBFrameRate.setMaximum(200)
        self.SBFrameRate.setProperty("value", 30)
        self.SBFrameRate.setObjectName("SBFrameRate")
        self.PBMakeV = QtWidgets.QPushButton(self.groupBox_7)
        self.PBMakeV.setGeometry(QtCore.QRect(80, 370, 75, 25))
        self.PBMakeV.setObjectName("PBMakeV")
        self.groupBox_11 = QtWidgets.QGroupBox(self.groupBox_7)
        self.groupBox_11.setGeometry(QtCore.QRect(0, 470, 261, 221))
        self.groupBox_11.setObjectName("groupBox_11")
        self.label_68 = QtWidgets.QLabel(self.groupBox_11)
        self.label_68.setGeometry(QtCore.QRect(50, 30, 71, 21))
        self.label_68.setObjectName("label_68")
        self.label_69 = QtWidgets.QLabel(self.groupBox_11)
        self.label_69.setGeometry(QtCore.QRect(80, 60, 51, 16))
        self.label_69.setObjectName("label_69")
        self.label_70 = QtWidgets.QLabel(self.groupBox_11)
        self.label_70.setGeometry(QtCore.QRect(80, 90, 51, 16))
        self.label_70.setObjectName("label_70")
        self.label_71 = QtWidgets.QLabel(self.groupBox_11)
        self.label_71.setGeometry(QtCore.QRect(20, 120, 101, 21))
        self.label_71.setObjectName("label_71")
        self.label_72 = QtWidgets.QLabel(self.groupBox_11)
        self.label_72.setGeometry(QtCore.QRect(50, 150, 61, 21))
        self.label_72.setObjectName("label_72")
        self.LEFrameRateF = QtWidgets.QLineEdit(self.groupBox_11)
        self.LEFrameRateF.setGeometry(QtCore.QRect(120, 30, 75, 25))
        self.LEFrameRateF.setObjectName("LEFrameRateF")
        self.LEDateF = QtWidgets.QLineEdit(self.groupBox_11)
        self.LEDateF.setGeometry(QtCore.QRect(120, 60, 75, 25))
        self.LEDateF.setObjectName("LEDateF")
        self.LEHourF = QtWidgets.QLineEdit(self.groupBox_11)
        self.LEHourF.setGeometry(QtCore.QRect(120, 90, 75, 25))
        self.LEHourF.setObjectName("LEHourF")
        self.LENFramesF = QtWidgets.QLineEdit(self.groupBox_11)
        self.LENFramesF.setGeometry(QtCore.QRect(120, 120, 75, 25))
        self.LENFramesF.setObjectName("LENFramesF")
        self.LETimeF = QtWidgets.QLineEdit(self.groupBox_11)
        self.LETimeF.setGeometry(QtCore.QRect(120, 150, 75, 25))
        self.LETimeF.setObjectName("LETimeF")
        self.TlistFrame = QtWidgets.QTreeView(self.groupBox_7)
        self.TlistFrame.setGeometry(QtCore.QRect(10, 60, 256, 192))
        self.TlistFrame.setSelectionMode(QtWidgets.QAbstractItemView.SingleSelection)
        self.TlistFrame.setObjectName("TlistFrame")
        self.toolBox.addItem(self.PGFEditor, "")
        self.PGVEditor = QtWidgets.QWidget()
        self.PGVEditor.setObjectName("PGVEditor")
        self.groupBox_8 = QtWidgets.QGroupBox(self.PGVEditor)
        self.groupBox_8.setGeometry(QtCore.QRect(0, 0, 271, 721))
        self.groupBox_8.setObjectName("groupBox_8")
        self.PBFolderVideo = QtWidgets.QPushButton(self.groupBox_8)
        self.PBFolderVideo.setGeometry(QtCore.QRect(10, 20, 75, 25))
        self.PBFolderVideo.setObjectName("PBFolderVideo")
        self.LEPATHVideo = QtWidgets.QLineEdit(self.groupBox_8)
        self.LEPATHVideo.setGeometry(QtCore.QRect(100, 20, 151, 25))
        self.LEPATHVideo.setObjectName("LEPATHVideo")
        self.PBOutputV = QtWidgets.QPushButton(self.groupBox_8)
        self.PBOutputV.setGeometry(QtCore.QRect(10, 270, 75, 25))
        self.PBOutputV.setObjectName("PBOutputV")
        self.LEOutPathV = QtWidgets.QLineEdit(self.groupBox_8)
        self.LEOutPathV.setGeometry(QtCore.QRect(100, 270, 151, 25))
        self.LEOutPathV.setObjectName("LEOutPathV")
        self.PBFrames = QtWidgets.QPushButton(self.groupBox_8)
        self.PBFrames.setGeometry(QtCore.QRect(80, 320, 75, 25))
        self.PBFrames.setObjectName("PBFrames")
        self.groupBox_12 = QtWidgets.QGroupBox(self.groupBox_8)
        self.groupBox_12.setGeometry(QtCore.QRect(10, 530, 251, 181))
        self.groupBox_12.setObjectName("groupBox_12")
        self.label_73 = QtWidgets.QLabel(self.groupBox_12)
        self.label_73.setGeometry(QtCore.QRect(50, 30, 71, 21))
        self.label_73.setObjectName("label_73")
        self.label_74 = QtWidgets.QLabel(self.groupBox_12)
        self.label_74.setGeometry(QtCore.QRect(80, 60, 51, 16))
        self.label_74.setObjectName("label_74")
        self.label_75 = QtWidgets.QLabel(self.groupBox_12)
        self.label_75.setGeometry(QtCore.QRect(80, 90, 51, 16))
        self.label_75.setObjectName("label_75")
        self.label_76 = QtWidgets.QLabel(self.groupBox_12)
        self.label_76.setGeometry(QtCore.QRect(20, 120, 101, 21))
        self.label_76.setObjectName("label_76")
        self.label_77 = QtWidgets.QLabel(self.groupBox_12)
        self.label_77.setGeometry(QtCore.QRect(50, 150, 61, 21))
        self.label_77.setObjectName("label_77")
        self.LEFrameRateV = QtWidgets.QLineEdit(self.groupBox_12)
        self.LEFrameRateV.setGeometry(QtCore.QRect(120, 30, 75, 25))
        self.LEFrameRateV.setObjectName("LEFrameRateV")
        self.LEDateV = QtWidgets.QLineEdit(self.groupBox_12)
        self.LEDateV.setGeometry(QtCore.QRect(120, 60, 75, 25))
        self.LEDateV.setObjectName("LEDateV")
        self.LEHourV = QtWidgets.QLineEdit(self.groupBox_12)
        self.LEHourV.setGeometry(QtCore.QRect(120, 90, 75, 25))
        self.LEHourV.setObjectName("LEHourV")
        self.LENFramesV = QtWidgets.QLineEdit(self.groupBox_12)
        self.LENFramesV.setGeometry(QtCore.QRect(120, 120, 75, 25))
        self.LENFramesV.setObjectName("LENFramesV")
        self.LETimeV = QtWidgets.QLineEdit(self.groupBox_12)
        self.LETimeV.setGeometry(QtCore.QRect(120, 150, 75, 25))
        self.LETimeV.setObjectName("LETimeV")
        self.TlistVideo = QtWidgets.QTreeView(self.groupBox_8)
        self.TlistVideo.setGeometry(QtCore.QRect(10, 60, 256, 192))
        self.TlistVideo.setObjectName("TlistVideo")
        self.groupBox_14 = QtWidgets.QGroupBox(self.groupBox_8)
        self.groupBox_14.setGeometry(QtCore.QRect(10, 350, 240, 170))
        self.groupBox_14.setObjectName("groupBox_14")
        self.groupBox_15 = QtWidgets.QGroupBox(self.groupBox_14)
        self.groupBox_15.setGeometry(QtCore.QRect(0, 140, 240, 30))
        self.groupBox_15.setTitle("")
        self.groupBox_15.setObjectName("groupBox_15")
        self.RBLGetFrame = QtWidgets.QRadioButton(self.groupBox_15)
        self.RBLGetFrame.setGeometry(QtCore.QRect(10, 10, 121, 17))
        self.RBLGetFrame.setObjectName("RBLGetFrame")
        self.groupBox_16 = QtWidgets.QGroupBox(self.groupBox_14)
        self.groupBox_16.setGeometry(QtCore.QRect(0, 110, 240, 30))
        self.groupBox_16.setTitle("")
        self.groupBox_16.setObjectName("groupBox_16")
        self.RBBGetFrame = QtWidgets.QRadioButton(self.groupBox_16)
        self.RBBGetFrame.setGeometry(QtCore.QRect(10, 10, 121, 17))
        self.RBBGetFrame.setObjectName("RBBGetFrame")
        self.groupBox_17 = QtWidgets.QGroupBox(self.groupBox_14)
        self.groupBox_17.setGeometry(QtCore.QRect(0, 80, 240, 30))
        self.groupBox_17.setTitle("")
        self.groupBox_17.setObjectName("groupBox_17")
        self.RBFGetFrame = QtWidgets.QRadioButton(self.groupBox_17)
        self.RBFGetFrame.setGeometry(QtCore.QRect(10, 10, 121, 17))
        self.RBFGetFrame.setObjectName("RBFGetFrame")
        self.groupBox_18 = QtWidgets.QGroupBox(self.groupBox_14)
        self.groupBox_18.setGeometry(QtCore.QRect(0, 50, 240, 30))
        self.groupBox_18.setTitle("")
        self.groupBox_18.setObjectName("groupBox_18")
        self.RBISGetFrame = QtWidgets.QRadioButton(self.groupBox_18)
        self.RBISGetFrame.setGeometry(QtCore.QRect(10, 10, 121, 17))
        self.RBISGetFrame.setObjectName("RBISGetFrame")
        self.groupBox_19 = QtWidgets.QGroupBox(self.groupBox_14)
        self.groupBox_19.setGeometry(QtCore.QRect(0, 20, 240, 30))
        self.groupBox_19.setTitle("")
        self.groupBox_19.setObjectName("groupBox_19")
        self.RBOGetFrame = QtWidgets.QRadioButton(self.groupBox_19)
        self.RBOGetFrame.setGeometry(QtCore.QRect(10, 10, 101, 17))
        self.RBOGetFrame.setChecked(True)
        self.RBOGetFrame.setObjectName("RBOGetFrame")
        self.toolBox.addItem(self.PGVEditor, "")
        self.gridLayout.addWidget(self.toolBox, 0, 0, 3, 1)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.TWImageV = QtWidgets.QTabWidget(self.centralwidget)
        self.TWImageV.setObjectName("TWImageV")
        self.TaSimage = QtWidgets.QWidget()
        self.TaSimage.setObjectName("TaSimage")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.TaSimage)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.GVImage = ImageView(self.TaSimage)
        self.GVImage.setObjectName("GVImage")
        self.verticalLayout_5.addWidget(self.GVImage)
        self.gridLayout_2.addLayout(self.verticalLayout_5, 0, 0, 1, 1)
        self.TWImageV.addTab(self.TaSimage, "")
        self.TaProcess = QtWidgets.QWidget()
        self.TaProcess.setObjectName("TaProcess")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.TaProcess)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.gridLayout_3 = QtWidgets.QGridLayout()
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.TWImageA = ImageView(self.TaProcess)
        self.TWImageA.setObjectName("TWImageA")
        self.gridLayout_3.addWidget(self.TWImageA, 0, 0, 1, 1)
        self.TWImageB = ImageView(self.TaProcess)
        self.TWImageB.setObjectName("TWImageB")
        self.gridLayout_3.addWidget(self.TWImageB, 0, 1, 1, 1)
        self.TWImageC = ImageView(self.TaProcess)
        self.TWImageC.setObjectName("TWImageC")
        self.gridLayout_3.addWidget(self.TWImageC, 1, 0, 1, 1)
        self.TWImageD = ImageView(self.TaProcess)
        self.TWImageD.setObjectName("TWImageD")
        self.gridLayout_3.addWidget(self.TWImageD, 1, 1, 1, 1)
        self.gridLayout_4.addLayout(self.gridLayout_3, 0, 0, 1, 1)
        self.TWImageV.addTab(self.TaProcess, "")
        self.verticalLayout_2.addWidget(self.TWImageV)
        self.gridLayout.addLayout(self.verticalLayout_2, 0, 1, 1, 1)
        self.label_11 = QtWidgets.QLabel(self.centralwidget)
        self.label_11.setMaximumSize(QtCore.QSize(16777215, 10))
        self.label_11.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_11.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_11.setObjectName("label_11")
        self.gridLayout.addWidget(self.label_11, 2, 1, 1, 1)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.PBPVideo = QtWidgets.QPushButton(self.centralwidget)
        self.PBPVideo.setObjectName("PBPVideo")
        self.horizontalLayout_5.addWidget(self.PBPVideo)
        self.PBResetLive = QtWidgets.QPushButton(self.centralwidget)
        self.PBResetLive.setObjectName("PBResetLive")
        self.horizontalLayout_5.addWidget(self.PBResetLive)
        self.PBReset_2 = QtWidgets.QPushButton(self.centralwidget)
        self.PBReset_2.setObjectName("PBReset_2")
        self.horizontalLayout_5.addWidget(self.PBReset_2)
        self.CBProcess = QtWidgets.QCheckBox(self.centralwidget)
        self.CBProcess.setChecked(True)
        self.CBProcess.setObjectName("CBProcess")
        self.horizontalLayout_5.addWidget(self.CBProcess)
        self.CBHist = QtWidgets.QCheckBox(self.centralwidget)
        self.CBHist.setChecked(True)
        self.CBHist.setObjectName("CBHist")
        self.horizontalLayout_5.addWidget(self.CBHist)
        self.PBFramesVideo = QtWidgets.QPushButton(self.centralwidget)
        self.PBFramesVideo.setObjectName("PBFramesVideo")
        self.horizontalLayout_5.addWidget(self.PBFramesVideo)
        self.PGBSaving = QtWidgets.QProgressBar(self.centralwidget)
        self.PGBSaving.setProperty("value", 0)
        self.PGBSaving.setObjectName("PGBSaving")
        self.horizontalLayout_5.addWidget(self.PGBSaving)
        self.gridLayout.addLayout(self.horizontalLayout_5, 1, 1, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1111, 21))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuEdit = QtWidgets.QMenu(self.menubar)
        self.menuEdit.setObjectName("menuEdit")
        self.menuView = QtWidgets.QMenu(self.menubar)
        self.menuView.setObjectName("menuView")
        self.menuHelp = QtWidgets.QMenu(self.menubar)
        self.menuHelp.setObjectName("menuHelp")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionNew = QtWidgets.QAction(MainWindow)
        self.actionNew.setObjectName("actionNew")
        self.actionOpen = QtWidgets.QAction(MainWindow)
        self.actionOpen.setObjectName("actionOpen")
        self.actionOpen_File_Type = QtWidgets.QAction(MainWindow)
        self.actionOpen_File_Type.setObjectName("actionOpen_File_Type")
        self.actionClose = QtWidgets.QAction(MainWindow)
        self.actionClose.setObjectName("actionClose")
        self.actionImport_Images = QtWidgets.QAction(MainWindow)
        self.actionImport_Images.setObjectName("actionImport_Images")
        self.actionImport_Video = QtWidgets.QAction(MainWindow)
        self.actionImport_Video.setObjectName("actionImport_Video")
        self.actionExit = QtWidgets.QAction(MainWindow)
        self.actionExit.setObjectName("actionExit")
        self.actionCut = QtWidgets.QAction(MainWindow)
        self.actionCut.setObjectName("actionCut")
        self.actionCopy = QtWidgets.QAction(MainWindow)
        self.actionCopy.setObjectName("actionCopy")
        self.actionPaste = QtWidgets.QAction(MainWindow)
        self.actionPaste.setObjectName("actionPaste")
        self.actionToolbars = QtWidgets.QAction(MainWindow)
        self.actionToolbars.setObjectName("actionToolbars")
        self.actionStatus_bar = QtWidgets.QAction(MainWindow)
        self.actionStatus_bar.setObjectName("actionStatus_bar")
        self.actionCamera_Pane = QtWidgets.QAction(MainWindow)
        self.actionCamera_Pane.setObjectName("actionCamera_Pane")
        self.actionEditor_Pane = QtWidgets.QAction(MainWindow)
        self.actionEditor_Pane.setObjectName("actionEditor_Pane")
        self.actionSequence_Pane = QtWidgets.QAction(MainWindow)
        self.actionSequence_Pane.setObjectName("actionSequence_Pane")
        self.actionAnalysis_Pane = QtWidgets.QAction(MainWindow)
        self.actionAnalysis_Pane.setObjectName("actionAnalysis_Pane")
        self.menuFile.addAction(self.actionNew)
        self.menuFile.addAction(self.actionOpen)
        self.menuFile.addAction(self.actionOpen_File_Type)
        self.menuFile.addAction(self.actionClose)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionImport_Images)
        self.menuFile.addAction(self.actionImport_Video)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionExit)
        self.menuEdit.addAction(self.actionCut)
        self.menuEdit.addAction(self.actionCopy)
        self.menuEdit.addAction(self.actionPaste)
        self.menuView.addAction(self.actionToolbars)
        self.menuView.addAction(self.actionStatus_bar)
        self.menuView.addSeparator()
        self.menuView.addAction(self.actionCamera_Pane)
        self.menuView.addAction(self.actionEditor_Pane)
        self.menuView.addAction(self.actionSequence_Pane)
        self.menuView.addAction(self.actionAnalysis_Pane)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuEdit.menuAction())
        self.menubar.addAction(self.menuView.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(MainWindow)
        self.toolBox.setCurrentIndex(2)
        self.TABCamera.setCurrentIndex(1)
        self.TBBGK.setCurrentIndex(0)
        self.TWImageV.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.groupBox_5.setTitle(_translate("MainWindow", "Set"))
        self.PBCheckCam.setText(_translate("MainWindow", "Check Camera"))
        self.groupBox_2.setTitle(_translate("MainWindow", "Camera Control"))
        self.PBLive.setText(_translate("MainWindow", "Live"))
        self.label.setText(_translate("MainWindow", "Exposure:"))
        self.label_2.setText(_translate("MainWindow", "ms"))
        self.label_4.setText(_translate("MainWindow", "Bits:"))
        self.CBBits_2.setItemText(0, _translate("MainWindow", "8"))
        self.CBBits_2.setItemText(1, _translate("MainWindow", "10"))
        self.CBBits_2.setItemText(2, _translate("MainWindow", "12"))
        self.CBBits_2.setItemText(3, _translate("MainWindow", "14"))
        self.CBBits_2.setItemText(4, _translate("MainWindow", "16"))
        self.label_6.setText(_translate("MainWindow", "Contrast Gain:"))
        self.CBBits.setItemText(0, _translate("MainWindow", "8"))
        self.CBBits.setItemText(1, _translate("MainWindow", "10"))
        self.CBBits.setItemText(2, _translate("MainWindow", "12"))
        self.groupBox_3.setTitle(_translate("MainWindow", "Array"))
        self.CBBinning.setItemText(0, _translate("MainWindow", "1"))
        self.CBBinning.setItemText(1, _translate("MainWindow", "2"))
        self.CBBinning.setItemText(2, _translate("MainWindow", "4"))
        self.CBBinning.setItemText(3, _translate("MainWindow", "Customize"))
        self.label_5.setText(_translate("MainWindow", "X0_Position:"))
        self.PBApply.setText(_translate("MainWindow", "Apply"))
        self.label_3.setText(_translate("MainWindow", "Binning:"))
        self.label_7.setText(_translate("MainWindow", "Y0_Position:"))
        self.CBBinning_2.setItemText(0, _translate("MainWindow", "1"))
        self.CBBinning_2.setItemText(1, _translate("MainWindow", "2"))
        self.CBBinning_2.setItemText(2, _translate("MainWindow", "Customize"))
        self.PBReset.setText(_translate("MainWindow", "Reset"))
        self.label_9.setText(_translate("MainWindow", "Height"))
        self.label_8.setText(_translate("MainWindow", "Width"))
        self.TABCamera.setTabText(self.TABCamera.indexOf(self.TABDevice), _translate("MainWindow", "Device"))
        self.groupBox_4.setTitle(_translate("MainWindow", "Subtractor"))
        self.RBImage.setText(_translate("MainWindow", "Image Default"))
        self.TBBGK.setItemText(self.TBBGK.indexOf(self.POriginal), _translate("MainWindow", "Original Image"))
        self.label_16.setText(_translate("MainWindow", "Min Pixel Stability:"))
        self.RBTCNT.setText(_translate("MainWindow", "Background Subtractor CNT"))
        self.label_15.setText(_translate("MainWindow", "<html><head/><body><p>Min Pixel Stability:</p></body></html>"))
        self.CBHistory.setText(_translate("MainWindow", "Use History"))
        self.CBIsParallel.setText(_translate("MainWindow", "Is Parallel"))
        self.TBBGK.setItemText(self.TBBGK.indexOf(self.PBKGCNT), _translate("MainWindow", "Background Subtractor CNT"))
        self.label_17.setText(_translate("MainWindow", "Initial Frame:"))
        self.label_18.setText(_translate("MainWindow", "Threshold:"))
        self.RBTGMG.setText(_translate("MainWindow", "Background Subtractor GMG"))
        self.TBBGK.setItemText(self.TBBGK.indexOf(self.PBKGGMG), _translate("MainWindow", "Background Subtractor GMG"))
        self.RBTGSOC.setText(_translate("MainWindow", "Background Subtractor GSOC"))
        self.label_19.setText(_translate("MainWindow", "# Samples:"))
        self.label_20.setText(_translate("MainWindow", "Threshold:"))
        self.label_21.setText(_translate("MainWindow", "Replace Rate:"))
        self.label_22.setText(_translate("MainWindow", "alpha:"))
        self.label_23.setText(_translate("MainWindow", "beta:"))
        self.label_24.setText(_translate("MainWindow", "Propagation Rate:"))
        self.TBBGK.setItemText(self.TBBGK.indexOf(self.PBKGGSOC), _translate("MainWindow", "Background Subtractor GSOC"))
        self.RBTKNN.setText(_translate("MainWindow", "Background Subtractor KNN"))
        self.label_25.setText(_translate("MainWindow", "History:"))
        self.label_26.setText(_translate("MainWindow", "Dist to Threshold:"))
        self.checkBox.setText(_translate("MainWindow", "Detect Shadows"))
        self.TBBGK.setItemText(self.TBBGK.indexOf(self.PBKGKNN), _translate("MainWindow", "Background Subtractor KNN"))
        self.RBTLSBP.setText(_translate("MainWindow", "Background Subtractor LSBP"))
        self.label_27.setText(_translate("MainWindow", "# Samples:"))
        self.label_28.setText(_translate("MainWindow", "LSBP Radius:"))
        self.label_29.setText(_translate("MainWindow", "R Scale:"))
        self.label_30.setText(_translate("MainWindow", "LSBP Threshold:"))
        self.label_32.setText(_translate("MainWindow", "min Count"))
        self.label_33.setText(_translate("MainWindow", "T Upper:"))
        self.TBBGK.setItemText(self.TBBGK.indexOf(self.PBKGLSBP), _translate("MainWindow", "Background Subtractor LSBP"))
        self.RBTMOG.setText(_translate("MainWindow", "Background Subtractor MOG"))
        self.label_31.setText(_translate("MainWindow", "History: "))
        self.label_34.setText(_translate("MainWindow", "# Mixtures: "))
        self.label_35.setText(_translate("MainWindow", "Background Ratio:"))
        self.label_36.setText(_translate("MainWindow", "Noise Sigma:"))
        self.TBBGK.setItemText(self.TBBGK.indexOf(self.PBKGMOG), _translate("MainWindow", "Background Subtractor MOG"))
        self.RBTMOG2.setText(_translate("MainWindow", "Background Subtractor MOG2"))
        self.label_37.setText(_translate("MainWindow", "History:"))
        self.label_38.setText(_translate("MainWindow", "Threshold:"))
        self.CBDshadowsMOG2.setText(_translate("MainWindow", "SHADOWS"))
        self.TBBGK.setItemText(self.TBBGK.indexOf(self.PBKGMOG2), _translate("MainWindow", "Background Subtractor MOG2"))
        self.RBTRNB.setText(_translate("MainWindow", "Background Subtractor RNB"))
        self.label_39.setText(_translate("MainWindow", "Alpha: "))
        self.label_40.setText(_translate("MainWindow", "Threshold Thu:"))
        self.label_41.setText(_translate("MainWindow", "Threshold Ths:"))
        self.TBBGK.setItemText(self.TBBGK.indexOf(self.PBKGRNB), _translate("MainWindow", "Background Subtractor RNB"))
        self.RBTFZBL.setText(_translate("MainWindow", "Background Subtractor FZBL"))
        self.label_42.setText(_translate("MainWindow", "Threshold Thfs:"))
        self.label_43.setText(_translate("MainWindow", "Alpha: "))
        self.label_44.setText(_translate("MainWindow", "Threshold Ths:"))
        self.TBBGK.setItemText(self.TBBGK.indexOf(self.PBKGFZBL), _translate("MainWindow", "Background Subtractor FZBL"))
        self.RBTFZB.setText(_translate("MainWindow", "Background Subtractor FZB"))
        self.label_45.setText(_translate("MainWindow", "Threshold Ths:"))
        self.label_46.setText(_translate("MainWindow", "Threshold Thfs:"))
        self.label_47.setText(_translate("MainWindow", "Alpha: "))
        self.label_48.setText(_translate("MainWindow", "Alpha Min: "))
        self.TBBGK.setItemText(self.TBBGK.indexOf(self.PBKGFZB), _translate("MainWindow", "Background Subtractor FZB"))
        self.groupBox_6.setTitle(_translate("MainWindow", "Image"))
        self.RBOFrame.setText(_translate("MainWindow", "Original Frame"))
        self.RBBFrame.setText(_translate("MainWindow", "Background Frame"))
        self.RBFFrame.setText(_translate("MainWindow", "Foreground Frame"))
        self.RBImg.setText(_translate("MainWindow", "Image Subtractor"))
        self.label_49.setText(_translate("MainWindow", "α"))
        self.label_51.setText(_translate("MainWindow", "β"))
        self.PBApplyBGK.setText(_translate("MainWindow", "APPLY"))
        self.RBLImg.setText(_translate("MainWindow", "Lapse Image"))
        self.label_50.setText(_translate("MainWindow", "α"))
        self.label_52.setText(_translate("MainWindow", "β"))
        self.TABCamera.setTabText(self.TABCamera.indexOf(self.TABBackground), _translate("MainWindow", "Background"))
        self.TABCamera.setTabText(self.TABCamera.indexOf(self.TABFilters), _translate("MainWindow", "Filters"))
        self.groupBox_9.setTitle(_translate("MainWindow", "Frames"))
        self.PBSetF.setText(_translate("MainWindow", "Folder"))
        self.groupBox.setTitle(_translate("MainWindow", "Control"))
        self.RBFrames.setText(_translate("MainWindow", "End Frame:"))
        self.RBtime.setText(_translate("MainWindow", "End Time:"))
        self.label_10.setText(_translate("MainWindow", "sec"))
        self.PBAcquire.setText(_translate("MainWindow", "Acquire"))
        self.LEFileP.setPlaceholderText(_translate("MainWindow", "File Path"))
        self.PBLive_2.setText(_translate("MainWindow", "Live"))
        self.groupBox_10.setTitle(_translate("MainWindow", "Output Frames"))
        self.label_53.setText(_translate("MainWindow", "Frame Rate:"))
        self.label_54.setText(_translate("MainWindow", "Date:"))
        self.label_55.setText(_translate("MainWindow", "Time:"))
        self.label_56.setText(_translate("MainWindow", "Number of Frames:"))
        self.label_57.setText(_translate("MainWindow", "Lapse Time:"))
        self.TABCamera.setTabText(self.TABCamera.indexOf(self.TABGet), _translate("MainWindow", "Get Frames"))
        self.toolBox.setItemText(self.toolBox.indexOf(self.PGCamera), _translate("MainWindow", "Camera"))
        self.groupBox_7.setTitle(_translate("MainWindow", "Frame List"))
        self.PBFolderFrame.setText(_translate("MainWindow", "Input Folder"))
        self.LEPATH.setPlaceholderText(_translate("MainWindow", "File Path"))
        self.PBOutputF.setText(_translate("MainWindow", "Output Folder"))
        self.LEOutPath.setPlaceholderText(_translate("MainWindow", "File Path"))
        self.label_13.setText(_translate("MainWindow", "Frame Rate:"))
        self.PBMakeV.setText(_translate("MainWindow", "Make Video"))
        self.groupBox_11.setTitle(_translate("MainWindow", "Output Frames"))
        self.label_68.setText(_translate("MainWindow", "Frame Rate:"))
        self.label_69.setText(_translate("MainWindow", "Date:"))
        self.label_70.setText(_translate("MainWindow", "Time:"))
        self.label_71.setText(_translate("MainWindow", "Number of Frames:"))
        self.label_72.setText(_translate("MainWindow", "Lapse Time:"))
        self.toolBox.setItemText(self.toolBox.indexOf(self.PGFEditor), _translate("MainWindow", "Frames Editor"))
        self.groupBox_8.setTitle(_translate("MainWindow", "Video List"))
        self.PBFolderVideo.setText(_translate("MainWindow", "Input Folder"))
        self.LEPATHVideo.setPlaceholderText(_translate("MainWindow", "File Path"))
        self.PBOutputV.setText(_translate("MainWindow", "Output Folder"))
        self.LEOutPathV.setPlaceholderText(_translate("MainWindow", "File Path"))
        self.PBFrames.setText(_translate("MainWindow", "Make Frames"))
        self.groupBox_12.setTitle(_translate("MainWindow", "Output Frames"))
        self.label_73.setText(_translate("MainWindow", "Frame Rate:"))
        self.label_74.setText(_translate("MainWindow", "Date:"))
        self.label_75.setText(_translate("MainWindow", "Time:"))
        self.label_76.setText(_translate("MainWindow", "Number of Frames:"))
        self.label_77.setText(_translate("MainWindow", "Lapse Time:"))
        self.groupBox_14.setTitle(_translate("MainWindow", "Image"))
        self.RBLGetFrame.setText(_translate("MainWindow", "Lapse Image"))
        self.RBBGetFrame.setText(_translate("MainWindow", "Background Frame"))
        self.RBFGetFrame.setText(_translate("MainWindow", "Foreground Frame"))
        self.RBISGetFrame.setText(_translate("MainWindow", "Image Subtractor"))
        self.RBOGetFrame.setText(_translate("MainWindow", "Original Frame"))
        self.toolBox.setItemText(self.toolBox.indexOf(self.PGVEditor), _translate("MainWindow", "Video Editor"))
        self.TWImageV.setTabText(self.TWImageV.indexOf(self.TaSimage), _translate("MainWindow", "Image"))
        self.TWImageV.setTabText(self.TWImageV.indexOf(self.TaProcess), _translate("MainWindow", "Process"))
        self.label_11.setText(_translate("MainWindow", "CCTR OJ1605 v1"))
        self.PBPVideo.setText(_translate("MainWindow", "Play Video"))
        self.PBResetLive.setText(_translate("MainWindow", "Reset"))
        self.PBReset_2.setText(_translate("MainWindow", "Pause Video"))
        self.CBProcess.setText(_translate("MainWindow", "Check Process"))
        self.CBHist.setText(_translate("MainWindow", "Histogram"))
        self.PBFramesVideo.setText(_translate("MainWindow", "Get Frames"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.menuEdit.setTitle(_translate("MainWindow", "Edit"))
        self.menuView.setTitle(_translate("MainWindow", "View"))
        self.menuHelp.setTitle(_translate("MainWindow", "Help"))
        self.actionNew.setText(_translate("MainWindow", "New"))
        self.actionOpen.setText(_translate("MainWindow", "Open"))
        self.actionOpen_File_Type.setText(_translate("MainWindow", "Open File Type"))
        self.actionClose.setText(_translate("MainWindow", "Close"))
        self.actionImport_Images.setText(_translate("MainWindow", "Import Images"))
        self.actionImport_Video.setText(_translate("MainWindow", "Import Video"))
        self.actionExit.setText(_translate("MainWindow", "Exit"))
        self.actionCut.setText(_translate("MainWindow", "Cut"))
        self.actionCopy.setText(_translate("MainWindow", "Copy"))
        self.actionPaste.setText(_translate("MainWindow", "Paste"))
        self.actionToolbars.setText(_translate("MainWindow", "Toolbars"))
        self.actionStatus_bar.setText(_translate("MainWindow", "Status bar"))
        self.actionCamera_Pane.setText(_translate("MainWindow", "Camera Pane"))
        self.actionEditor_Pane.setText(_translate("MainWindow", "Editor Pane"))
        self.actionSequence_Pane.setText(_translate("MainWindow", "Sequence Pane"))
        self.actionAnalysis_Pane.setText(_translate("MainWindow", "Analysis Pane"))
from pyqtgraph import ImageView


